### ISSUE TITLE
Link to roadmap broken

### ISSUE THREAD

**Issue by pongoman** [vui-kit/vui#2]
Hi there,

the link on the readme page `http://www.vui-kit.com/docs/getting-started/roadmap` redirects to 404 but website navigation to roadmap works fine.

Keep up the good work.

**Comment by jlomoglio** [comment]
Thank you letting me know, I removed the link. There is an issue with my hosting company, they are not allowing deep linking to my site.

**Comment by vui-kit** [comment]
Issue has been resolved
