### ISSUE TITLE
Looking for an icon plug-in

### ISSUE THREAD

**Issue by vsTianhao** [vui-kit/vui#3]
Hi there,
I saw a image in the documentation，I like those icons very much，Is this a plug-in in vscode？How to get it？

https://www.vui-kit.com/static/img/vui-src-dir.512bce7.png 
![here](https://www.vui-kit.com/static/img/vui-src-dir.512bce7.png)

**Comment by jlomoglio** [comment]
Here is where you can get the icons:

https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons
